### ISSUE TITLE
Uninitialized constant ActiveSupport::Autoload

### ISSUE THREAD

**Issue by patbl** [beeminder/beeminder-gem#10]
## Desiderata

- [x] Release new version of gem on 2022-04-19

---

I get the following error message and stack trace when I run `beemind` from the command line:

```
➜  ~  ruby-2.1.1 beemind
/home/pat/.rvm/gems/ruby-2.1.1/gems/activesupport-4.1.0/lib/active_support/number_helper.rb:3:in `<module:NumberHelper>': uninitialized constant ActiveSupport::Autoload (NameError)
        from /home/pat/.rvm/gems/ruby-2.1.1/gems/activesupport-4.1.0/lib/active_support/number_helper.rb:2:in `<module:ActiveSupport>'
        from /home/pat/.rvm/gems/ruby-2.1.1/gems/activesupport-4.1.0/lib/active_support/number_helper.rb:1:in `<top (required)>'
        from /home/pat/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
        from /home/pat/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
        from /home/pat/.rvm/gems/ruby-2.1.1/gems/activesupport-4.1.0/lib/active_support/core_ext/numeric/conversions.rb:2:in `<top (required)>'
        from /home/pat/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
        from /home/pat/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
        from /home/pat/.rvm/gems/ruby-2.1.1/gems/activesupport-4.1.0/lib/active_support/core_ext/numeric.rb:3:in `<top (required)>'
        from /home/pat/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
        from /home/pat/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
        from /home/pat/.rvm/gems/ruby-2.1.1/gems/activesupport-4.1.0/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
        from /home/pat/.rvm/gems/ruby-2.1.1/gems/activesupport-4.1.0/lib/active_support/core_ext.rb:1:in `each'
        from /home/pat/.rvm/gems/ruby-2.1.1/gems/activesupport-4.1.0/lib/active_support/core_ext.rb:1:in `<top (required)>'
        from /home/pat/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
        from /home/pat/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
        from /home/pat/.rvm/gems/ruby-2.1.1/gems/beeminder-0.2.10/lib/beeminder.rb:3:in `<top (required)>'
        from /home/pat/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
        from /home/pat/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
        from /home/pat/.rvm/gems/ruby-2.1.1/gems/beeminder-0.2.10/bin/beemind:15:in `<top (required)>'
        from /home/pat/.rvm/gems/ruby-2.1.1/bin/beemind:23:in `load'
        from /home/pat/.rvm/gems/ruby-2.1.1/bin/beemind:23:in `<main>'
        from /home/pat/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
        from /home/pat/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
```

I tried uninstalling and reinstalling the gem, but to no avail. I'm using Ruby 2.1.1 and RVM. It's working fine on my other computer, so it may be a problem with my setup.

## Cognata

* #11

_**Verbata**: dev env, old ruby versions,_

**Comment by daniel-light** [comment]
32d1943561b622e0d754752f24d19663a3156509 fixes this issue for me, but isn't included in the version of gem I get from `gem install beeminder` on ruby 2.3.1. Can that be updated or is there something else it's waiting on?

**Comment by kingdonb** [comment]
Yeah I just noticed this too, fresh installation of the gem and I needed to add `require 'active_support'` at the top of this file (`lib/beeminder.rb`):

```
# coding: utf-8

require 'active_support'
require 'active_support/core_ext'
```

...but here it is in master branch.  This is beeminder-gem v0.2.10.

I also noticed that this gem is locked to `rails '< 5.0'` – I've got some ruby chops, is there anyone around or is there a current maintainer who needs help with this?

**Comment by kingdonb** [comment]
(This probably only affects people who don't have 'rails' in their gemfile, I've got one beedata that I've built on rails with capybara that needed upgrades to survive past last week, and I've got another one with JSON-only data that didn't need rails, but needed this fix...)

I got it to work by pointing at the git repo and master branch, so the fix in there should really probably be cut into a new gem!  There are other issues that should be addressed too, like for example trollop has been renamed and so you get this warning in my daily script:

```
Fetching git://github.com/beeminder/beeminder-gem.git
Fetching gem metadata from https://rubygems.org/.......
Resolving dependencies...
Using concurrent-ruby 1.0.5
Using i18n 0.9.5
Using minitest 5.11.3
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 4.2.10
Using awesome_print 1.6.1
Using chronic 0.10.2
Using highline 1.7.10
Using json 2.1.0 (was 1.8.3)
Using trollop 2.9.9
Using beeminder 0.2.11 (was 0.2.10) from git://github.com/beeminder/beeminder-gem.git (at master@88d7928)
Using bundler 1.16.4
Using sequel 4.31.0
Using sqlite3 1.3.11
Bundle complete! 5 Gemfile dependencies, 15 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
yebyen@martyfunkhouser:~/projects/YebMinder/BeeMinute$ bundle exec ./20graph.rb
time to update beeminder data, sending: 76.0
beemind -t [AUTH TOKEN] 20-minutes '76.0' 'from beeminute auto'
[DEPRECATION] This gem has been renamed to optimist and will no longer be supported. Please switch to optimist as soon as possible.```

(but it's working... but someone should look at it... 🙌 )

**Comment by bsoule** [comment]
Looks like we haven't done a release of the gem since april 2014, and the fix in https://github.com/beeminder/beeminder-gem/commit/32d1943561b622e0d754752f24d19663a3156509 wasn't merged until 2016, so I'll need to do a new release of the gem. bee.commits.to/new-beeminder-gem-release-v-2-11

And and enthusiastic YES! to PRs on this gem.

**Comment by kingdonb** [comment]
I submitted #18 which you can merge, that updates from `trollop` v2 to `optimist` v3.  I've upgraded my student-loan tracking Capybara app to Rails 5.2.1 against the master branch of beeminder-gem and it seems like everything's fine.  It's a daily job that runs a no-op if nothing has changed at the source table, so it could be Wednesday before the interest recalculates and I get to see for sure.  Will report back if anything topples over, but I think that's unlikely.

Again another instance where the latest release is missing a fix that already hit master.  #17 already was merged which fixed Rails 5 support.  Otherwise I think we really just need to cut a new release.

**Comment by kingdonb** [comment]
This one can also be closed with 0.2.11

**Comment by kingdonb** [comment]
@bsoule is there anything I can do to help with getting a new release tagged?

**Comment by matkoniecz** [comment]
Currently band aid with adding

> require 'active_support'

fails with

> Unable to activate beeminder-0.2.10, because activesupport-5.2.1 conflicts with activesupport (< 5, >= 3.2) (Gem::ConflictError)

**Comment by matkoniecz** [comment]
I found a workaround at https://stackoverflow.com/a/11767563/4130619

> sudo gem install specific_install
> sudo gem specific_install -l https://github.com/beeminder/beeminder-gem.git

**Comment by bsoule** [comment]
The latest version of beeminder gem, 0.2.13, was released on April 19 2022, so four years after this  last message, and includes the commit that kingdon referenced above, that adds ActiveSupport to the gemspec.
