### ISSUE TITLE
uninitialized constant ActiveSupport::Deprecation (NameError)

### ISSUE THREAD

**Issue by aaronpk** [beeminder/beeminder-gem#11]
I am trying to make a really simple command line script to update beeminder, but getting this error when running it.

I have a Gemfile with:

```
source 'https://rubygems.org'
gem 'beeminder'
```

and a ruby file with:

```ruby
require 'beeminder'
```

Running the script I get a nasty error

```
/Users/aaronpk/.gem/ruby/1.9.3/gems/activesupport-4.2.0/lib/active_support/core_ext/module/deprecation.rb:21:in `deprecate': uninitialized constant ActiveSupport::Deprecation (NameError)
	from /Users/aaronpk/.gem/ruby/1.9.3/gems/activesupport-4.2.0/lib/active_support/core_ext/class/delegating_attributes.rb:26:in `<class:Class>'
	from /Users/aaronpk/.gem/ruby/1.9.3/gems/activesupport-4.2.0/lib/active_support/core_ext/class/delegating_attributes.rb:6:in `<top (required)>'
...
```

I get the same error in Ruby 1.9.3. and 2.1.3.

I don't really know what's going on.

**Comment by bsoule** [comment]
This: https://github.com/rails/rails/issues/12876 says it ought to have been fixed on 4.0.0 :(

**Comment by aaronpk** [comment]
What are you using activesupport for anyway? Can you just remove the dependency?

**Comment by bsoule** [comment]
That was my first question too. Not sure, but it looks like maybe some date/time stuff? don't know what else.

**Comment by muflax** [comment]
Yes, activesupport is only really used to handle timezones:

https://github.com/beeminder/beeminder-gem/commit/092a500d381b22d1c050961d19292751ee5e00b9
https://github.com/beeminder/beeminder-gem/commit/e7df1a5702e82670c27e0166f827ce9ec4c2ee83

**Comment by jerzygangi** [comment]
+1 for removing the ActiveSupport dependency. For such a simple API client, vanilla ruby would be preferred.

**Comment by kingdonb** [comment]
```
kbarret8@kbarret8-mbp:~/beem (master *)$ bundle exec ruby file.rb
kbarret8@kbarret8-mbp:~/beem (master *)$ cat Gemfile
source 'https://rubygems.org'
gem 'beeminder', git: 'git@github.com:beeminder/beeminder-gem'


kbarret8@kbarret8-mbp:~/beem (master *)$ cat Gemfile.lock
GIT
  remote: git@github.com:beeminder/beeminder-gem
  revision: 88d79287886828e66637c1663be3fb93fcf4d73b
  specs:
    beeminder (0.2.11)
      activesupport (>= 3.2, < 6)
```

I think this can be closed for the 2.11 release, it appears to be fixed in master.
